Fix functional/tempest v2 failures
gate_hook: Fix INSTALL_MYSQL_ONLY != True case

(cherry picked from commit 2a4cffb77a4337b9f0ae1c03131c7adb74ea8965)

Add a variant of gate hook script

I plan to use this for gate-neutron-fwaas-{fwaas-version}-dsvm-tempest
to populate NETWORK_API_EXTENSIONS.

(cherry picked from commit 8af9d55670bbf9571b870915ceda2808330736e8)

Closes-bug: 1661420
Closes-bug: 1661419

Add Tempest API tests for FWaaS v2.
Partially-Implements: blueprint fwaas-api-2.0

(cherry picked from commit 7880f27d15b104d88e8a017aef56100dea3aff28)

Fix tempest gate issue on FirewallNotFound exception

In case of failed tests the following error appears in
logs/screen-q-svc.txt.gz

  File "/opt/stack/new/neutron-fwaas/neutron_fwaas/db/firewall/v2/firewall_db_v2.py", line 805, in delete_firewall_group
    raise fw_ext.FirewallNotFound(firewall_id=id)
AttributeError: 'module' object has no attribute 'FirewallNotFound'

This exception doesn't exists anymore.
It has been replaced by FirewallGroupNotFound exception.

Closes-Bug: #1649703
Closes-Bug: #1657299
(cherry picked from commit 8a86782c229537ab430cac87b5df63a9ddd5424c)

Change-Id: I625146043c7589f0935fcc9a5043b36d5eb763d5