Fix AttributeError with third-party L3 service plugins
A recent patch fix for the Rocky branch from
commit 20fd02611674da5365e93d06f330d1f76fd71e3e have introduced an
AttributeError on Third Party Plugins that does not implement
certain extensions.

This is just related to FWaaSv1 and only applicable to Rocky and below
releases.

This change fixes an issue where in the course of sending firewall
update notifications to the appropriate agents an AttributeError
is encountered due to unsafe assumption of the availability of L3
extensions on the l3_plugin.

This change puts protections in place to avoid this issue.

Change-Id: If5fde4fc9475f468860b0c1fb29db66f1c44f74e
Closes-Bug: #1847019
(cherry picked from commit fc59b08ff78456c98fee0cc187f8888bc99c333e)