Use assert(Not)In instead of assertTrue/False
Neutron tests should use:

self.assertIn(value, list) and
self.assertNotIn(value, list)

instead of:

self.assertTrue(value in list) and
self.assertFalse(value in list)

because assertIn and assertNotIn raise more meaningful errors:

self.assertIn(3, [1, 2])
>>> MismatchError: 3 not in [1, 2]

self.assertTrue(3 in [1, 2])
>>> AssertionError: False is not true

To enforce this improvement, this patch is created.

Change-Id: Ia2ca003829858cceda181da41dea4f70a3d48d45
Related-Bug: #1218713